# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs-20_x", "python3"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

# Cache node_modules
[build]
buildCommand = "npm ci --include=dev --no-audit --no-fund && npm run build"