[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300

[nixpacks]
nixlibs = ["nodejs-20_x"]
aptPkgs = []

[[services]]
[services.environments.production]
variables = { NODE_ENV = "production" }